spring.application.name=aadi-foodie
#db configurations
spring.datasource.url=jdbc:mysql://localhost:3306/aadi-foodie
spring.datasource.username=root
spring.datasource.password=8003640485@Mysql
#spring.datasource.password=8003640485@Sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# jpa and hibernate configurations
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.ddl-auto=update
